### ISSUE TITLE
CSL-Daily数据集

### ISSUE THREAD

**Issue by lzy910** [hulianyuyy/AdaBrowse#4]
不好意思 还是关于csl数据集该如何训练的问题 phoenix2014的数据预处理文件会生成一个resize后的文件夹 里面存有256x256的数据 但是运行了phoenix2014-T和CSL-Daily的数据预处理文件后 只生成了标注文件夹 并没有生成resize后的文件夹 并无法完成训练 这是什么问题呢？

**Comment by hulianyuyy** [comment]
你可以把你的运行命令贴在这里，我给看一下吗？

**Comment by lzy910** [comment]
import re
import os
import cv2
import pdb
import glob
import pandas
import argparse
import numpy as np
from tqdm import tqdm
from functools import partial
from multiprocessing import Pool


def csv2dict(anno_path, dataset_type):
    inputs_list = pandas.read_csv(anno_path)
    inputs_list = (inputs_list.to_dict()['name|video|start|end|speaker|orth|translation'].values())
    info_dict = dict()
    info_dict['prefix'] = anno_path.rsplit("/", 3)[0] + "/features/fullFrame-210x260px"
    print(f"Generate information dict from {anno_path}")
    for file_idx, file_info in tqdm(enumerate(inputs_list), total=len(inputs_list)):
        name, video, start, end, speaker, orth, translation = file_info.split("|")
        num_frames = len(glob.glob(f"{info_dict['prefix']}/{dataset_type}/{video}"))
        info_dict[file_idx] = {
            'fileid': name,
            'folder': f"{dataset_type}/{video}",
            'signer': speaker,
            'label': orth,
            'num_frames': num_frames,
            'original_info': file_info,
        }
    return info_dict


def generate_gt_stm(info, save_path):
    with open(save_path, "w") as f:
        for k, v in info.items():
            if not isinstance(k, int):
                continue
            f.writelines(f"{v['fileid']} 1 {v['signer']} 0.0 1.79769e+308 {v['label']}\n")


def sign_dict_update(total_dict, info):
    for k, v in info.items():
        if not isinstance(k, int):
            continue
        split_label = v['label'].split()
        for gloss in split_label:
            if gloss not in total_dict.keys():
                total_dict[gloss] = 1
            else:
                total_dict[gloss] += 1
    return total_dict


def resize_img(img_path, dsize='210x260px'):
    dsize = tuple(int(res) for res in re.findall("\d+", dsize))
    img = cv2.imread(img_path)
    img = cv2.resize(img, dsize, interpolation=cv2.INTER_LANCZOS4)
    return img


def resize_dataset(video_idx, dsize, info_dict):
    info = info_dict[video_idx]
    img_list = glob.glob(f"{info_dict['prefix']}/{info['folder']}")
    for img_path in img_list:
        rs_img = resize_img(img_path, dsize=dsize)
        rs_img_path = img_path.replace("210x260px", dsize)
        rs_img_dir = os.path.dirname(rs_img_path)
        if not os.path.exists(rs_img_dir):
            os.makedirs(rs_img_dir)
            cv2.imwrite(rs_img_path, rs_img)
        else:
            cv2.imwrite(rs_img_path, rs_img)


def run_mp_cmd(processes, process_func, process_args):
    with Pool(processes) as p:
        outputs = list(tqdm(p.imap(process_func, process_args), total=len(process_args)))
    return outputs


def run_cmd(func, args):
    return func(args)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Data process for Visual Alignment Constraint for Continuous Sign Language Recognition.')
    parser.add_argument('--dataset', type=str, default='phoenix2014-T',
                        help='save prefix')
    parser.add_argument('--dataset-root', type=str, default='/home/pickleball/公共的/oldli/VAC_CSLR-main/dataset/phoenix-2014-T.v3/PHOENIX-2014-T-release-v3/PHOENIX-2014-T',
                        help='path to the dataset')
    parser.add_argument('--annotation-prefix', type=str, default='annotations/manual/PHOENIX-2014-T.{}.corpus.csv',
                        help='annotation prefix')
    parser.add_argument('--output-res', type=str, default='256x256px',
                        help='resize resolution for image sequence')
    parser.add_argument('--process-image', '-p', action='store_true',
                        help='resize image')
    parser.add_argument('--multiprocessing', '-m', action='store_true',
                        help='whether adopts multiprocessing to accelate the preprocess')

    args = parser.parse_args()
    mode = ["dev", "test", "train"]
    sign_dict = dict()
    if not os.path.exists(f"./{args.dataset}"):
        os.makedirs(f"./{args.dataset}")
    for md in mode:
        # generate information dict
        information = csv2dict(f"{args.dataset_root}/{args.annotation_prefix.format(md)}", dataset_type=md)
        np.save(f"./{args.dataset}/{md}_info.npy", information)
        # update the total gloss dict
        sign_dict_update(sign_dict, information)
        # generate groudtruth stm for evaluation
        generate_gt_stm(information, f"./{args.dataset}/{args.dataset}-groundtruth-{md}.stm")
        # resize images
        video_index = np.arange(len(information) - 1)
        print(f"Resize image to {args.output_res}")
        if args.process_image:
            if args.multiprocessing:
                run_mp_cmd(10, partial(resize_dataset, dsize=args.output_res, info_dict=information), video_index)
            else:
                for idx in tqdm(video_index):
                    run_cmd(partial(resize_dataset, dsize=args.output_res, info_dict=information), idx)
                    #resize_dataset(idx, dsize=args.output_res, info_dict=information)
    sign_dict = sorted(sign_dict.items(), key=lambda d: d[0])
    save_dict = {}
    for idx, (key, value) in enumerate(sign_dict):
        save_dict[key] = [idx + 1, value]
    np.save(f"./{args.dataset}/gloss_dict.npy", save_dict)
这是根据您的预处理文件所运行的 我把dataset-root改为我数据集所在路径，控制台也会输出resize image to256x256px 但是在dataset/phoenix2014-T/features这个路径下没有生成256x256的文件夹

**Comment by hulianyuyy** [comment]
你当时运行这个命令，命令大概运行了多久。一般需要数十分钟，如果过短时间比如几秒钟，可能没有读取到图片，所以就没有执行resize操作

**Comment by lzy910** [comment]
运行了不到一分钟，我也感觉他根本没有resize，我也对ph2014的预处理文件重新测试过，要很久，所以我想清教您是什么原因导致没有resize到呢，文件的路径是没问题的。

**Comment by hulianyuyy** [comment]
一般来说是源路径设置错误，要设置到`PATH_TO_DATASET/PHOENIX-2014-T-release-v3/PHOENIX-2014-T`这个层级上。或者对于phoenix2014-t数据集来说，也会有这个[问题](https://github.com/hulianyuyy/CorrNet/issues/10#issuecomment-1660363025)。

**Comment by lzy910** [comment]
这是PHOENIX-2014-T的目录
├── annotations
│   └── manual
├── evaluation
│   ├── README
│   ├── sign-recognition
│   └── sign-translation
├── features
│   └── fullFrame-210x260px
└── models
    └── languagemodels
parser.add_argument('--dataset-root', type=str, default='/home/pickleball/公共的/oldli/VAC_CSLR-main/dataset/phoenix-2014-T.v3/PHOENIX-2014-T-release-v3/PHOENIX-2014-T',
                        help='path to the dataset') 这个参数已经设置到该目录了

**Comment by hulianyuyy** [comment]
那你看看是不是存在上面那个问题，并且建议不要设置中文目录

**Comment by lzy910** [comment]
按照该问题成功解决了 谢谢您的帮助 祝您生活愉快 paper多多 稍后可能还会有关于CSL-Daily的问题向您请教 我是个小白 还需要多向您学习

**Comment by lzy910** [comment]
Loading model
/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model finished.
Loading data
train 5671
Apply training transform.

train 5671
Apply testing transform.

dev 540
Apply testing transform.

test 629
Apply testing transform.

Loading data finished.
.git does not exist in current dir
[ Tue Dec  3 17:34:42 2024 ] Parameters:
{'work_dir': 'run', 'config': 'configs/baseline.yaml', 'random_fix': True, 'device': '0', 'phase': 'train', 'save_interval': 5, 'random_seed': 0, 'eval_interval': 1, 'print_log': True, 'log_interval': 50, 'evaluate_tool': 'sclite', 'feeder': 'dataset.dataloader_video.BaseFeeder', 'dataset': 'phoenix2014-T', 'dataset_info': {'dataset_root': './dataset/phoenix-2014-T.v3/PHOENIX-2014-T-release-v3/PHOENIX-2014-T', 'dict_path': './preprocess/phoenix2014-T/gloss_dict.npy', 'evaluation_dir': './evaluation/slr_eval', 'evaluation_prefix': 'phoenix2014-T-groundtruth'}, 'num_worker': 10, 'feeder_args': {'mode': 'test', 'datatype': 'video', 'num_gloss': -1, 'drop_ratio': 1.0, 'prefix': './dataset/phoenix-2014-T.v3/PHOENIX-2014-T-release-v3/PHOENIX-2014-T', 'transform_mode': False}, 'model': 'slr_network.SLRModel', 'model_args': {'num_classes': 1116, 'c2d_type': 'resnet18', 'conv_type': 2, 'use_bn': 1, 'share_classifier': False, 'weight_norm': False}, 'load_weights': None, 'load_checkpoints': None, 'decode_mode': 'beam', 'ignore_weights': [], 'batch_size': 2, 'test_batch_size': 8, 'loss_weights': {'SeqCTC': 1.0}, 'optimizer_args': {'optimizer': 'Adam', 'base_lr': 0.0001, 'step': [40, 60], 'learning_ratio': 1, 'weight_decay': 0.0001, 'start_epoch': 0, 'nesterov': False}, 'num_epoch': 70}

  0%|                                                                                                                                                                                                                        | 0/2835 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 229, in <module>
    processor.start()
  File "main.py", line 57, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "/home/pickleball/公共的/oldli/VAC_CSLR-main/seq_scripts.py", line 18, in seq_train
    for batch_idx, data in enumerate(tqdm(loader)):
  File "/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pickleball/anaconda3/envs/vac/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pickleball/公共的/oldli/VAC_CSLR-main/dataset/dataloader_video.py", line 47, in __getitem__
    input_data, label = self.normalize(input_data, label)
  File "/home/pickleball/公共的/oldli/VAC_CSLR-main/dataset/dataloader_video.py", line 78, in normalize
    video, label = self.data_aug(video, label, file_id)
  File "/home/pickleball/公共的/oldli/VAC_CSLR-main/utils/video_augmentation.py", line 24, in __call__
    image = t(image)
  File "/home/pickleball/公共的/oldli/VAC_CSLR-main/utils/video_augmentation.py", line 120, in __call__
    if isinstance(clip[0], np.ndarray):
IndexError: list index out of range
不好意思我又来麻烦您了 现在预处理搞好了 但是训练时还是报这个错误
dataset_root: ./dataset/phoenix-2014-T.v3/PHOENIX-2014-T-release-v3/PHOENIX-2014-T
dict_path: ./preprocess/phoenix2014-T/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: phoenix2014-T-groundtruth
这是ph2014-T的yaml文件
feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: phoenix2014-T
# dataset: phoenix14-si5
num_epoch: 70
work_dir: ./work_dir/baseline_res18/
batch_size: 2
random_seed: 0
test_batch_size: 8
num_worker: 10
device: 0,1
log_interval: 50
eval_interval: 1
save_interval: 5
# python in default
evaluate_tool: sclite
loss_weights:
  SeqCTC: 1.0
  # VAC
  # ConvCTC: 1.0
  # Dist: 10.0
#load_weights: ''

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 40, 60]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

model: slr_network.SLRModel
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: resnet18
  
  conv_type: 2
  use_bn: 1
  # SMKD
  share_classifier: False
  weight_norm: False
这是baseline.yaml

**Comment by hulianyuyy** [comment]
一般来说是数据集路径设置不太对，所以没有读取到图片。你之前的问题是按照哪个思路解决的，在phoenix2014-T数据集路径下多了一个`1`的目录吗

**Comment by lzy910** [comment]
import os
import shutil

dir_path = "/home/pickleball/公共的/oldli/VAC_CSLR-main/dataset/phoenix-2014-T.v3/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px/train"
subfolders = [x for x in os.listdir(dir_path) if os.path.isdir(os.path.join(dir_path, x))]

for dir in subfolders:
    if "1" in os.listdir(os.path.join(dir_path, dir)):
        continue # 1 dir already exists, assume files are in correct dir
    files = [x for x in os.listdir(os.path.join(dir_path, dir)) if os.path.isfile(os.path.join(dir_path, dir, x))]
    goal_dir = os.path.join(dir_path, dir, "1")
    os.makedirs(goal_dir)
    for f in files:
        shutil.move(os.path.join(dir_path, dir, f), goal_dir)
根据这个代码解决的 /home/pickleball/公共的/oldli/VAC_CSLR-main/dataset/phoenix-2014-T.v3/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-256x256px/dev/01April_2010_Thursday_heute-6697/1/images0001.png 他将每天的文件夹中创建了1的文件夹

**Comment by hulianyuyy** [comment]
那你可以检查一下，在./dataset/dataloader_video.py的第68行之后，输出一下`img_folder`的值，看看和实际上视频的位置是不是一致

**Comment by lzy910** [comment]
![微信图片_20241217132423](https://github.com/user-attachments/assets/dd75a138-5731-4e49-a6d4-53d12733ade6)
是一致的 但是我发现它每个视频的文件夹01August_2011_Monday_heute-4859 后面有个编号例如4859 而打印出来的img_folder后面是default

**Comment by hulianyuyy** [comment]
可能是现在的视频被发布者改了一下路径，和我当初编码的时候不一致了。你可以在dataset_preprocess.py中改一下数据的路径。
